/**
 * Builds the patch decoder (wasm/qoi_wasm.c + wasm/lz4_wasm.c, LZ4 from the patch-codec package's vendor directory) with plain
 * `clang --target=wasm32` and `wasm-ld`: no Emscripten, no libc. The result, about 2 KB, is written as a TypeScript
 * module (src/patch/wasm-bytes.ts, generated, not committed) so the viewer and its tests import the bytes directly.
 *
 * Build requirements: clang and lld (`apt install clang lld`). The linker is `wasm-ld` or `wasm-ld-18` on PATH, or
 * the file named by $WASM_LD.
 */
import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const buildDir = path.join(root, 'wasm', 'build')
const lz4Dir = path.join(root, '..', 'patch-codec', 'native', 'vendor')
const output = path.join(root, 'src', 'patch', 'wasm-bytes.ts')

function run(command, args) {
  const result = spawnSync(command, args, { stdio: 'inherit' })
  if (result.error || result.status !== 0) {
    console.error(`viewer: ${command} failed.`)
    process.exit(1)
  }
}

function find(names) {
  for (const name of names) {
    if (spawnSync(name, ['--version'], { stdio: 'ignore' }).status === 0) {
      return name
    }
  }
  return undefined
}

const clang = process.env.CLANG ?? find(['clang', 'clang-18'])
if (clang === undefined) {
  console.error('viewer: clang is needed to build the patch decoder for wasm (install clang and lld: apt install clang lld).')
  process.exit(1)
}
const wasmLd = process.env.WASM_LD ?? find(['wasm-ld', 'wasm-ld-18'])
if (wasmLd === undefined) {
  console.error('viewer: wasm-ld is needed to build the patch decoder for wasm: install lld (apt install lld).')
  process.exit(1)
}
if (!existsSync(path.join(lz4Dir, 'lz4.c'))) {
  console.error(`viewer: ${lz4Dir}/lz4.c is missing.`)
  process.exit(1)
}

mkdirSync(buildDir, { recursive: true })
const flags = ['--target=wasm32', '-O2', '-nostdlib', '-ffreestanding', '-mbulk-memory']
const objects = []
for (const [source, extra] of [
  ['qoi_wasm.c', []],
  ['lz4_wasm.c', ['-I' + lz4Dir]],
]) {
  const object = path.join(buildDir, source.replace(/\.c$/, '.o'))
  run(clang, [...flags, ...extra, '-c', path.join(root, 'wasm', source), '-o', object])
  objects.push(object)
}
const wasm = path.join(buildDir, 'patch-decode.wasm')
// The memory is fixed at 24 MB (see patch-decoder.ts for the layout) and the stack is 64 KB.
run(wasmLd, [
  '--no-entry',
  '--export=qoi_decode_into',
  '--export=lz4_decompress',
  '--export=__heap_base',
  '--export-memory',
  `--initial-memory=${24 << 20}`,
  `--max-memory=${24 << 20}`,
  '-z',
  'stack-size=65536',
  '--gc-sections',
  '--strip-all',
  '-o',
  wasm,
  ...objects,
])
const bytes = readFileSync(wasm)
writeFileSync(
  output,
  `// Generated by scripts/build-wasm.mjs from wasm/*.c, don't edit and don't commit.\n` +
    `export const PATCH_DECODER_WASM_BASE64 = '${bytes.toString('base64')}'\n`,
)
console.log(`viewer: patch decoder built (${bytes.length} bytes of wasm)`)
