name: CI
on:
  push:
    branches:
      - master
      - login-gateway
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    # 24.04: wlroots 0.17 needs its libwayland (1.22) and wayland-protocols
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          clean: 'true'
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build tools
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends autoconf libtool automake pipx ninja-build bison cmake build-essential gperf

      - name: Compositor Proxy build dependencies
        run: |
          sudo apt-get -y remove 'libunwind-*' || true
          sudo apt-get -y install --no-install-recommends libudev-dev libdrm-dev libegl-dev libopengl-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libgraphene-1.0-dev

      - name: wlroots build dependencies
        run: |
          sudo apt-get -y install --no-install-recommends meson libwayland-dev wayland-protocols libpixman-1-dev libxkbcommon-dev libgbm-dev libgles-dev

      - name: Install
        run: yarn install # will run `yarn install` command

      - name: Build
        run: yarn build

      - name: Unit tests
        run: |
          yarn workspace @gfld/compositor-proxy test
          yarn workspace @gfld/viewer test
